Fitter/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from . import views as fitter_views

urlpatterns = [
    url(r'^', include('fitterKakao.urls')),
    url(r'^admin/', admin.site.urls),
    url(
        r'^accounts/login/',
        auth_views.login,
        name='login',
        kwargs={
            'template_name': 'fitterKakao/login.html',
        }
    ),
    url(
        r'^accounts/logout/',
        auth_views.logout,
        name='logout',
        kwargs={
            'next_page': settings.LOGOUT_REDIRECT_URL,
        }
    ),
    url(r'^accounts/signup$', fitter_views.CreateUser.as_view(), name='signup'),
    url(r'^accounts/signup/done$', fitter_views.registered, name='create_user_done'),

]

fitterKakao/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views  # .은 현재 디렉토리 의미
from django.conf import settings
from django.conf.urls.static import static

app_name = 'fitterKakao'
urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^result/(?P<kinds>[a-z]+)/(?P<tag_num>[0-9]+)/$', views.suppose_size, name='suppose_size'),
    url(r'^new/$', views.post_new, name='post_new'),
    url(r'^edit/(?P<user_name>[a-zA-Z0-9@.+-_]+)/$', views.post_edit, name='post_edit'),
    url(r'^clothes/$', views.choose_clothes, name='choose_clothes'),
    url(r'^clothes/new/(?P<kinds>[a-z]+)/$', views.add_clothes, name='add_clothes'),
    url(r'^clothes/del/(?P<kinds>[a-z]+)/(?P<tag_num>[0-9]+)/$', views.delete_clothes, name='delete_clothes'),
    url(r'^clothes/edit/(?P<kinds>[a-z]+)/(?P<tag_num>[0-9]+)/$', views.edit_clothes, name='edit_clothes'),
    url(r'^single/$', views.single_mode, name='single_mode'),
    url(r'^single/body/(?P<kinds>[a-z]+)/$', views.single_post_body, name='single_post_body'),
    url(r'^single/between/(?P<kinds>[a-z]+)/$', views.single_post_between, name='single_post_between'),
    url(r'^queer/$', views.data_add, name='data_add'),
    url(r'^gaaay/$', views.data_del, name='data_del'),
    # url(r'^keyboard/', views.keyboard), # 카톡
    # url(r'^message', views.answer), # 카톡
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fitterKakao/models.py
from django.db import models
from django.conf import settings
from django_resized import ResizedImageField

required = '채워주세요.'
class SizeInfo(models.Model):
    MAN = 'man'; WOMAN = 'woman'
    SEX_CHOICES = [(MAN, '남자'), (WOMAN, '여자')]
    sex = models.CharField(max_length=5, choices=SEX_CHOICES, default=WOMAN)
    weight = models.IntegerField(default=0)
    height = models.IntegerField(default=0)
    shoulder = models.CharField(max_length=40, default=None)
    chest = models.CharField(max_length=40, default=None)
    arm = models.CharField(max_length=40, default=None)
    waist = models.CharField(max_length=40, default=None)
    bottom_waist = models.CharField(max_length=40, default=None)
    crotch = models.CharField(max_length=40, default=None)
    thigh = models.CharField(max_length=40, default=None)
    length = models.CharField(max_length=40, default=None)
    hem = models.CharField(max_length=40, default=None)
    hip = models.CharField(max_length=40, default=None)
    crotch_height = models.CharField(max_length=40, default=None)
    middle_thigh = models.CharField(max_length=40, default=None)
    knee = models.CharField(max_length=40, default=None)
    calf = models.CharField(max_length=40, default=None)
    nipple = models.CharField(max_length=40, default=None)

    def __str__(self):  # Change title as name(메소드처럼)
        return r"%s %s %s" % (self.sex, str(self.height), str(self.weight))



class Person(models.Model):
    SMALL =0; AVG = 1; BIG = 2
    CHOICES = [(SMALL, '작다'), (AVG, '보통'), (BIG, '크다')]
    MAN = 'man'; WOMAN = 'woman'
    SEX_CHOICES = [(MAN, '남자'), (WOMAN, '여자')]
    name = models.ForeignKey(settings.AUTH_USER_MODEL)
    sex = models.CharField(max_length=5, choices=SEX_CHOICES, default=WOMAN)
    weight = models.IntegerField(default=0)
    height = models.IntegerField(default=0)
    # 상의
    shoulder_a = models.IntegerField(choices=CHOICES, default=AVG)
    chest_a = models.IntegerField(choices=CHOICES, default=AVG)
    sleeve_a = models.IntegerField(choices=CHOICES, default=AVG)
    waist_a = models.IntegerField(choices=CHOICES, default=AVG)
    # 하의
    hip_a = models.IntegerField(choices=CHOICES, default=AVG)
    crotch_a = models.IntegerField(choices=CHOICES, default=AVG)
    length_a = models.IntegerField(choices=CHOICES, default=AVG)
    thigh_a = models.IntegerField(choices=CHOICES, default=AVG)
    hem_a = models.IntegerField(choices=CHOICES, default=AVG)

    def __str__(self):  # Change title as name(메소드처럼)
        return self.name.username


class CriteriaTop(models.Model):
    cri_top_length = models.FloatField(default=0)
    cri_shoulder = models.FloatField(default=0)
    cri_chest = models.FloatField(default=0)
    cri_sleeve = models.FloatField(default=0)


class CriteriaBottom(models.Model):
    cri_bot_length = models.FloatField(default=0)
    cri_waist = models.FloatField(default=0)
    cri_hip = models.FloatField(default=0)
    cri_crotch = models.FloatField(default=0)
    cri_thigh = models.FloatField(default=0)
    cri_hem = models.FloatField(default=0)


class SameClothes(models.Model):
    same_nick = models.CharField(max_length=80, default='Untitled')
    same_photo = ResizedImageField(blank=True, size=[300, 300], upload_to="%Y/%m/%d")
    same_url = models.URLField(blank=True, default='')

    def __str__(self):  # Change title as name(메소드처럼)
        return str(self.same_nick)


class TopClothes(models.Model):
    name = models.ForeignKey(settings.AUTH_USER_MODEL)
    photo = models.ForeignKey(SameClothes, on_delete=models.CASCADE, related_name='topclothes_photo_set')
    url = models.ForeignKey(SameClothes, on_delete=models.CASCADE, related_name='topclothes_url_set', null=True)
    nick = models.ForeignKey(SameClothes, on_delete=models.CASCADE, related_name='topclothes_nick_set')
    size = models.CharField(max_length=4, default='FREE')
    top_length = models.FloatField(default=0)
    shoulder = models.FloatField(default=0)
    chest = models.FloatField(default=0)
    sleeve = models.FloatField(default=0)

    def __str__(self):  # Change title as name(메소드처럼)
        print(self.nick.same_nick)
        return str(self.nick.same_nick)


class BottomClothes(models.Model):
    name = models.ForeignKey(settings.AUTH_USER_MODEL)
    photo = models.ForeignKey(SameClothes, on_delete=models.CASCADE, related_name='bottomclothes_photo_set')
    url = models.ForeignKey(SameClothes, on_delete=models.CASCADE, related_name='bottomclothes_url_set', null=True)
    nick = models.ForeignKey(SameClothes, on_delete=models.CASCADE, related_name='bottomclothes_nick_set')
    size = models.CharField(max_length=4, default='FREE')
    bot_length = models.FloatField(default=0)
    waist = models.FloatField(default=0)
    hip = models.FloatField(default=0)
    crotch = models.FloatField(default=0)
    thigh = models.FloatField(default=0)
    hem = models.FloatField(default=0)

    def __str__(self):  # Change title as name(메소드처럼)
        return str(self.nick.same_nick)


class SingleDataList(models.Model):
    suggested_size = models.CharField(max_length=800, default='{}')
    single_person_dict = models.CharField(max_length=800, default='{}')
    clothes_dict = models.CharField(max_length=800, default='{}')
    created = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):  # Change title as name(메소드처럼)
        return str(self.created)

fitterKakao/views.py
from django.shortcuts import render, redirect
from django.http import Http404, JsonResponse, HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from .models import Person, TopClothes, BottomClothes, SizeInfo, SameClothes, SingleDataList
import os

from django.conf import settings
from django.contrib.auth.decorators import login_required, user_passes_test
from django.forms.formsets import formset_factory, BaseFormSet
import json
from .forms import PersonForm, TopClothesForm, BottomClothesForm, SameClothesForm,\
                   CriteriaBottomForm,  CriteriaTopForm

def index(request):
    # reverse 는 url 하드코딩 피할수 있도록 해줌
    return render(request, 'fitterKakao/index.html')


def make_question_generator(whole_d):
    # data 과부하 줄이기
    for sex in ['man','woman']:
        shw_filtered_sizes = whole_d[sex]
        height_key = list(shw_filtered_sizes.keys())
        height_key = list(map(int, height_key))  # 원래 문자니까
        weight_range = range(15, 152) if sex =='man' else range(15, 105)
        for height in range(min(height_key), max(height_key)+10, 10):
            for weight in weight_range: # 해보니 그렇던데?/여자
                yield sex, height, weight


def read_json(fname, encoder):
    with open(fname, encoding=encoder) as data_file:
        json_data = json.load(data_file)
    return json_data


@user_passes_test(lambda u: u.is_superuser)
def data_add(request):
    file_path = os.path.join(settings.STATIC_ROOT, 'json/question_tree.json')
    question_tree = read_json(file_path, 'utf8')
    for sex, height, weight in make_question_generator(question_tree):
        print(sex, height, weight)
        parameters_data = question_tree[sex][str(height)][str(weight)]  # 자료가 있어야함
        try:
            if parameters_data:  # 데이터가 있다면
                size_info = SizeInfo(sex=sex, height=int(height), weight=int(weight))
                parameter_list = ['shoulder', 'chest', 'arm', 'waist',
                                  'bottom_waist', 'crotch', 'thigh', 'length', 'hem', 'hip',
                                  'crotch_height', 'middle_thigh', 'knee', 'calf', 'nipple']
                for parameter in parameter_list:
                    setattr(size_info, parameter, parameters_data[parameter])  # get attr

                size_info.save()
        except KeyError as e:
            continue

    return HttpResponse("DONE")


@user_passes_test(lambda u: u.is_superuser)
def data_del(request):
    SizeInfo.objects.all().delete()
    return HttpResponse("DEL DONE")


def size_list_to_dict(suggested_size):
    param_list = ['shoulder', 'chest', 'arm', 'waist',
                  'bottom_waist', 'crotch', 'thigh', 'length', 'hem', 'hip',
                  'crotch_height', 'middle_thigh', 'knee', 'calf', 'nipple']

    each_par_dict = {}
    for i, size in enumerate(suggested_size):
        each_par_dict[param_list[i]] = size
    return each_par_dict


def anticipate_size(user_name):
    """개인 답변으로 사이즈 추정하기"""
    person = Person.objects.filter(name=user_name)
    # 나중에 이거 [0]하는 부분 바꿔야함!
    person_info_dict = person.values('sex', 'height', 'weight', 'shoulder_a', 'chest_a', 'sleeve_a', 'waist_a',
                                     'hip_a', 'crotch_a', 'length_a', 'thigh_a', 'hem_a')[0]  # queryset
    # 키는 1770 이런 형식으로 되어있으므로 10 곱해야함
    user_sex = person_info_dict['sex']
    user_height, user_weight = person_info_dict['height'] * 10, person_info_dict['weight']

    # ['shoulder', 'chest', 'arm', 'waist'
    # 'bottom_waist', 'crotch', 'thigh', 'length', 'hem', 'hip',
    # 'crotch_height', 'middle_thigh', 'knee', 'calf', 'nipple'] 순서 질문지
    question = []
    for answer in ['shoulder_a', 'chest_a', 'sleeve_a', 'waist_a',
                   'waist_a', 'crotch_a', 'thigh_a', 'length_a', 'hem_a', 'hip_a',
                   'length_a', 'thigh_a', '', '', 'chest_a']:
        if len(answer) == 0:
            question.append(1)
        else:
            question.append(person_info_dict[answer])

    """DB 에서 데이터 찾기"""
    suggested_size_filter = \
        SizeInfo.objects.filter(sex=user_sex).filter(height=user_height).filter(weight=user_weight)

    """예상 사이즈 추천하고 실측 데이터로 바꾸기"""
    parameter_list = ['shoulder', 'chest', 'arm', 'waist',
                      'bottom_waist', 'crotch', 'thigh', 'length', 'hem', 'hip',
                      'crotch_height', 'middle_thigh', 'knee', 'calf', 'nipple']

    suggested_size = []
    for parameter, q in zip(parameter_list, question):
        # size info 에서 신체 부위별로 데이터 얻어오기
        parameter_dict = suggested_size_filter.values(parameter).first()[parameter]
        # 데이터가 dict 형식이므로 dict 로 바꾸기
        parameter_dict = json.loads(parameter_dict.replace("'", '"'))
        suggested_size.append(parameter_dict[str(q)])

    suggested_size = size_list_to_dict(suggested_size)

    return suggested_size

@login_required
def suppose_size(request, kinds, tag_num):
    try:
        person = Person.objects.filter(name=request.user)
        suggested_size = anticipate_size(request.user)

        if kinds == 'top':
            clothes = TopClothes.objects.filter(pk=tag_num)  # POST 한 정보만 보게?(일단 그냥 하나만 보게 하자)

        elif kinds == 'bot':
            clothes = BottomClothes.objects.filter(pk=tag_num)  # POST 한 정보만 보게?(일단 그냥 하나만 보게 하자)

    except TopClothes.DoesNotExist or BottomClothes.DoesNotExist:
        raise Http404("Data does not exist")

    return render(request, 'fitterKakao/result.html', {'types' : kinds,
                                                       'clothes': clothes,
                                                       'person': person,
                                                       'suggest_size': suggested_size, })


def check_data(d):
    exist = SizeInfo.objects.filter(sex=d['sex']).filter(height=d['height']*10).filter(weight=d['weight']).exists()

    return exist


@login_required
def post_new(request):
    if request.method == "POST": # 이미 보낸거라면
        person_form = PersonForm(request.POST)

        if person_form.is_valid(): # 저장된 form 형식이 잘 맞는지
            if not check_data(person_form.cleaned_data): # 없는 데이터라면,
                sex_filtered = SizeInfo.objects.filter(sex=person_form.cleaned_data['sex'])
                return render(request, 'fitterKakao/no_data.html', {'sex_filtered':sex_filtered,})

            person = person_form.save(commit=False) # False 바로 저장하지는 마
            person.name = request.user
            person.save()
            return redirect('fitterKakao:choose_clothes')
    else:
        person_form = PersonForm()

    return render(request, 'fitterKakao/post_new.html', {'person_form': person_form,})


@login_required
def post_edit(request, user_name):
    if not user_name == request.user.username:
        return render(request, 'fitterKakao/index.html')
    try:
        existing_data = Person.objects.get(name__username=user_name)
    except Person.DoesNotExist:
        return redirect('fitterKakao:post_new')

    if request.method == "POST":  # 이미 보낸거라면
        person_form = PersonForm(request.POST, instance=existing_data)
        if person_form.is_valid(): # 저장된 form 형식이 잘 맞는지
            if not check_data(person_form.cleaned_data): # 없는 데이터라면,
                sex_filtered = SizeInfo.objects.filter(sex=person_form.cleaned_data['sex'])
                return render(request, 'fitterKakao/no_data.html', {'sex_filtered':sex_filtered,})
            person = person_form.save(commit=False) # False 바로 저장하지는 마
            person.name = request.user
            person.save()
            return redirect('fitterKakao:choose_clothes')
    else:
        person_form = PersonForm(instance=existing_data)

    return render(request, 'fitterKakao/post_new.html', {'person_form': person_form, })


@login_required
def add_clothes(request, kinds):
    """한꺼번에 여러 옷들까지 추가할수 있는 기능(공통된 부분은 same_clothes 로)"""
    class RequiredFormSet(BaseFormSet):
        def __init__(self, *args, **kwargs):
            super(RequiredFormSet, self).__init__(*args, **kwargs)
            for form in self.forms:
                form.empty_permitted = False

    top_clothes_formset = formset_factory(TopClothesForm, max_num=3,
                                          formset=RequiredFormSet)
    bottom_clothes_formset = formset_factory(BottomClothesForm, max_num=3,
                                             formset=RequiredFormSet)

    if request.method == "POST":
        # 공통되는 부분 form
        same_clothes_form = SameClothesForm(request.POST, request.FILES)
        if kinds == 'top':
            clothes_formset = top_clothes_formset(request.POST, request.FILES)
            hashTag = '#top-clothes'
        elif kinds == 'bot':
            clothes_formset = bottom_clothes_formset(request.POST, request.FILES)
            hashTag = '#bottom-clothes'

        if clothes_formset.is_valid():
            same_clothes = same_clothes_form.save(commit=False)
            same_clothes.save()
            just_saved = SameClothes.objects.get(pk=same_clothes.pk)

            for form in clothes_formset.forms:
                clothes = form.save(commit=False)
                clothes.nick = just_saved
                clothes.url = just_saved
                clothes.photo = just_saved
                clothes.name = request.user
                clothes.save()

            return redirect('fitterKakao:suppose_size', kinds=kinds, tag_num=clothes.id)
    else:
        same_clothes_form = SameClothesForm()
        if kinds == 'top':
            clothes_formset = top_clothes_formset()
        elif kinds == 'bot':
            clothes_formset = bottom_clothes_formset()

    return render(request, 'fitterKakao/add_clothes.html', {'types' : kinds,
                                                            'clothes_formset': clothes_formset,
                                                            'same_clothes_form': same_clothes_form,})


@login_required
def edit_clothes(request, kinds, tag_num):
    # 데이터 내거인지 확인
    if kinds == 'top':

fitterKakao/templates/fitterKakao/single/single_between.html
{% extends "fitterKakao/single/single_post.html"%}
{%block inside%}
<h1 class="bodyCategory"> [옷 정보] </h1>
    {% if types == "top" %}
    <div class="item">

        <p><label for="id_same_nick">옷 이름:</label>
       <input id="id_same_nick" maxlength="80" name="same_nick" type="text" value="{{same_clothes_form.same_nick.value}}" required /></p>
        <p><label for="id_same_url">링크(선택):</label>
        {{same_clothes_form.same_url.errors}}
        <input id="id_same_url" maxlength="200" name="same_url" type="url" /></p>
        <label for="id_size">사이즈:</label>
        {{ clothes_form.size.errors }}
        <p><input id="id_size" maxlength="4" name="size" type="text" value="{{ clothes_form.size.value }}" /></p>
        <label for="id_top_length">길이:</label>
         {{ clothes_form.top_length.errors }}
        <p><input id="id_top_length" name="top_length" step="any" type="number" value="{{ clothes_form.top_length.value }}" /><span class ="unit">cm</span></p>
        <label for="id_shoulder">어깨:</label>
         {{ clothes_form.shoulder.errors }}
        <p><input id="id_shoulder" name="shoulder" step="any" type="number" value="{{ clothes_form.shoulder.value }}" /><span class ="unit">cm</span></p>
        <label for="id_chest">가슴:</label>
        {{ clothes_form.chest.errors }}
        <p><input id="id_chest" name="chest" step="any" type="number" value="{{ clothes_form.chest.value }}" /><span class ="unit">cm</span></p>
        <label for="id_sleeve">소매:</label>
        {{ clothes_form.sleeve.errors }}
        <p><input id="id_sleeve" name="sleeve" step="any" type="number" value="{{ clothes_form.sleeve.value }}" /><span class ="unit">cm</span></p>
    </div>
    {% elif types == "bot" %}
    <div class="item">

        <p><label for="id_same_nick">옷 이름:</label>
        <input id="id_same_nick" maxlength="80" name="same_nick" type="text" value="{{same_clothes_form.same_nick.value}}" required /></p>
        <p><label for="id_same_url">링크(선택):</label>
        {{same_clothes_form.same_url.errors}}
        <input id="id_same_url" maxlength="200" name="same_url" type="url" /></p>
        <label for="id_size">사이즈:</label>
        {{ clothes_form.size.errors }}
        <p><input id="id_size" maxlength="4" name="size" type="text" value="{{ clothes_form.size.value }}" /></p>
        <label for="id_waist">허리:</label>
        {{ clothes_form.waist.errors }}
        <p><input id="id_waist" name="waist" step="any" type="number" value="{{ clothes_form.waist.value }}" /><span class ="unit">cm</span></p>
        <label for="id_bot_length">기장:</label>
        {{ clothes_form.bot_length.errors }}
        <p><input id="id_bot_length" name="bot_length" step="any" type="number" value="{{ clothes_form.bot_length.value }}" /><span class ="unit">cm</span></p>

        <label for="id_crotch">밑위:</label>
        {{ clothes_form.crotch.errors }}
        <p><input id="id_crotch" name="crotch" step="any" type="number" value="{{ clothes_form.crotch.value }}" /><span class ="unit">cm</span></p>
        <label for="id_thigh">허벅지:</label>
        {{ clothes_form.thigh.errors }}
        <p><input id="id_thigh" name="thigh" step="any" type="number" value="{{ clothes_form.thigh.value }}" /><span class ="unit">cm</span></p>
        <label for="id_hem">밑단:</label>
        {{ clothes_form.hem.errors }}
        <p><input id="id_hem" name="hem" step="any" type="number" value="{{ clothes_form.hem.value }}" /><span class ="unit">cm</span></p>
        <p class ="greyer"><label><input type="checkbox" id= "hip_check" name="hip_exist" value="no"> 엉덩이 부분은 몰라요</label></p>
        <label for="id_hip" class = "hip">엉덩이:</label>
        {{ clothes_form.hip.errors }}
        <p><input id="id_hip" name="hip" step="any" type="number" value="{{ clothes_form.hip.value }}" /><span class ="unit">cm</span></p>

    </div>
    {% endif %}
    <div class = "info">

        {% if types == "top" %}
        <img src="{% static 'pic/top.png' %}">
        <p><span class ="impInfo">인터넷 쇼핑몰의 치수 데이터</span>를 입력해주세요.</p>
        <p>옷을 바닥에 <span class ="impInfo">눕혀서 잰 길이</span>로 계산해주세요.</p>
        <p>만약 가슴이라면 옷 앞부분 가슴길이만 잽니다.</p>
        {% elif types == "bot" %}
        <img src="{% static 'pic/bottom.png' %}">
        <p><span class ="impInfo">인터넷 쇼핑몰의 치수 데이터</span>를 입력해주세요.</p>
        <p>옷을 바닥에 <span class ="impInfo">눕혀서 잰 길이</span>로 계산해주세요.</p>
        <p>만약 허리라면 바지 앞부분 허리길이만 잽니다.</p>
        {% endif %}
    </div>
    <button type="submit" class ="btn btn-success btn-lg">결과보기</button>
{% endblock %}

fitterKakao/templates/fitterKakao/single/single_post_between.html
{% extends "fitterKakao/single/single_post.html"%}
{%block inside%}
<h1 class="bodyCategory"> [옷 종류] </h1>
    <div class = "clothes_type">
        <div id = "radioBtn" class="btn-group">
            {% if types == 'top' %}
            <a href="#" class="btn btn-outline-secondary btn-lg active" >상의</a>
            <a href="{% url 'fitterKakao:single_post_between' kinds='bot' %}" class="btn btn-outline-secondary btn-lg notActive">하의</a>
            {% elif types == 'bot' %}
            <a href="{% url 'fitterKakao:single_post_between' kinds='top' %}" class="btn btn-outline-secondary btn-lg notActive">상의</a>
            <a href="#" class="btn btn-outline-secondary btn-lg active">하의</a>
            {% endif %}
        </div>
    </div>

<h1 class="bodyCategory"> [기준 옷 정보] </h1>
    {% if types == "top" %}
    <div class="item">
        <label for="id_cri_top_length">길이:</label>
         {{ clothes_form.top_length.errors }}
        <p><input id="id_cri_top_length" name="cri_top_length" step="any" type="number" value="{{ criteria_form.cri_top_length.value }}" /><span class ="unit">cm</span></p>
        <label for="id_cri_shoulder">어깨:</label>
         {{ clothes_form.shoulder.errors }}
        <p><input id="id_cri_shoulder" name="cri_shoulder" step="any" type="number" value="{{ criteria_form.cri_shoulder.value }}" required /><span class ="unit">cm</span></p>
        <label for="id_cri_chest">가슴:</label>
        {{ clothes_form.chest.errors }}
        <p><input id="id_cri_chest" name="cri_chest" step="any" type="number" value="{{ criteria_form.cri_chest.value }}" required /><span class ="unit">cm</span></p>
        <label for="id_cri_sleeve">소매:</label>
        {{ clothes_form.sleeve.errors }}
        <p><input id="id_cri_sleeve" name="cri_sleeve" step="any" type="number" value="{{ criteria_form.cri_sleeve.value }}" required /><span class ="unit">cm</span></p>
    </div>
    {% elif types == "bot" %}
    <div class="item">
        <label for="id_cri_waist">허리:</label>
        {{ clothes_form.waist.errors }}
        <p> <input id="id_cri_waist" name="cri_waist" step="any" type="number" value="{{ criteria_form.cri_waist.value }}" required /><span class ="unit">cm</span></p>
        <label for="id_cri_bot_length">기장:</label>
        {{ clothes_form.bot_length.errors }}
        <p><input id="id_cri_bot_length" name="cri_bot_length" step="any" type="number" value="{{ criteria_form.cri_bot_length.value }}" required /><span class ="unit">cm</span></p>
        <label for="id_cri_crotch">밑위:</label>
        {{ clothes_form.crotch.errors }}
        <p><input id="id_cri_crotch" name="cri_crotch" step="any" type="number" value="{{ criteria_form.cri_crotch.value }}" required /><span class ="unit">cm</span></p>
        <label for="id_cri_thigh">허벅지:</label>
        {{ clothes_form.thigh.errors }}
        <p><input id="id_cri_thigh" name="cri_thigh" step="any" type="number" value="{{ criteria_form.cri_thigh.value }}" required /><span class ="unit">cm</span></p>
        <label for="id_cri_hem">밑단:</label>
        {{ clothes_form.hem.errors }}
        <p> <input id="id_cri_hem" name="cri_hem" step="any" type="number" value="{{ criteria_form.cri_hem.value }}" required /><span class ="unit">cm</span></p>
        <p class ="greyer"><label><input type="checkbox" id= "hip_check" name="hip_exist" value="no"> 엉덩이 부분은 몰라요</label></p>
        <label for="id_cri_hip" class = "hip">엉덩이:</label>
        {{ clothes_form.hip.errors }}
        <p><input id="id_cri_hip" name="cri_hip" step="any" type="number" value="{{ criteria_form.cri_hip.value }}" required /><span class ="unit">cm</span></p>

    </div>
    {% endif %}
{% endblock %}